use_frameworks!
platform :ios, '10.0'

target 'AnchoredBottomSheet_Example' do
  pod 'AnchoredBottomSheet', :path => '../'

  target 'AnchoredBottomSheet_Tests' do
    inherit! :search_paths    
  end
end
